#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

freezer_agent_bin_dir: "{{ 'freezer-agent' | bin_dir() }}"
freezer_agent_conf_dir: "{{ 'freezer-agent' | config_dir() }}"

# Logging
freezer_agent_log_dir: "/var/log/freezer-agent"
freezer_agent_log_file: "{{ freezer_agent_log_dir }}/freezer-agent.log"
freezer_scheduler_log_file: "{{ freezer_agent_log_dir }}/freezer-scheduler.log"

# Freezer scheduler options
freezer_client_id: "{{ old_deployer_hostname | default(ansible_hostname) }}"

freezer_agent_restart_required: false

freezer_scheduler_command: "source {{ freezer_agent_conf_dir }}/backup.osrc && freezer-scheduler -c {{ freezer_client_id }} -l {{ freezer_scheduler_log_file }}"
