#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: setup group
  group: name={{monasca_group}} system=yes
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: Setup user
  user: name={{monasca_api_user}} system=yes group={{monasca_group}}
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: Ensure vertica jdbc permissions
  file: path={{ vertica_jdbc_location }} mode=644
  when: database_type == 'vertica'

- name: Detect if this is a systemd based system
  command: cat /proc/1/comm
  register: init
- set_fact: use_systemd=True
  when: init.stdout == 'systemd'
- set_fact: use_systemd=False
  when: init.stdout != 'systemd'

- name: create systemd config
  template: dest={{api_systemd_service}} owner=root group=root mode=644 src=monasca-api.service.j2
  notify:
    - monasca-api | restart | restart all monasca-api services
  when: use_systemd

- command: systemctl daemon-reload
  when: use_systemd

- name: create upstart script from template
  template: dest=/etc/init/monasca-api.conf owner=root group=root mode=744 src=monasca-api.conf.j2
  notify:
    - monasca-api | restart | restart all monasca-api services
  when: not use_systemd

- name: create monasca log dir
  file: path={{monasca_log_dir}} state=directory owner=root group={{monasca_group}} mode=775
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: create api log dir
  file: path={{api_log_dir}} state=directory owner=root group={{monasca_group}} mode=775
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: stat /etc/monasca/api-config.yml file
  stat: path=/etc/monasca/api-config.yml
  register: api_conf_file_result

- name: move api-config.yml to api-config.yml.old if not a symlink
  command: mv /etc/monasca/api-config.yml /etc/monasca/api-config.yml.old
  when: api_conf_file_result.stat.exists and api_conf_file_result.stat.isreg

- name: create conf_file from template
  template: dest={{ monasca_api_conf_file }} owner={{monasca_api_user}} group={{monasca_group}} mode=640 src=api-config.yml.j2
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: link /etc/monasca/api-config.yml to service config dir
  file:
    path: /etc/monasca/api-config.yml
    src: "{{ 'monasca' | config_dir() }}/api-config.yml"
    state: link
    owner: "{{monasca_api_user}}"
    group: "{{monasca_group}}"
    mode: 640

- name: Copy Truststore
  copy: dest={{monasca_api_truststore}} src={{monasca_api_truststore_src}}
  when: monasca_api_truststore_src is defined
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: Copy Client Keystore
  copy: dest={{monasca_api_client_keystore}} src={{monasca_api_client_keystore_src}}
  when: monasca_api_client_keystore_src is defined
  notify:
    - monasca-api | restart | restart all monasca-api services

- name: Copy Keystore
  copy: dest={{monasca_api_keystore}} src={{monasca_api_keystore_src}}
  when: monasca_api_keystore_src is defined
  notify:
    - monasca-api | restart | restart all monasca-api services

- meta: flush_handlers
