#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Select default tunings based on system RAM
# RAM < 32GB, use demo
# RAM < 64GB, use small
# RAM < 128GB, use medium
# RAM >= 128GB, use large
tuning_selector: "{% if ansible_memtotal_mb < 32086 %}demo{% elif ansible_memtotal_mb < 64172 %}small{% elif ansible_memtotal_mb < 128344 %}medium{% else %}large{%endif %}"
monasca_possible_tunings:
    demo:
        kafka_heap_opts: "-Xmx128m"
        monasca_api_java_opts: "-Xmx128m"
        monasca_notification_alarm_processors: 1
        monasca_notification_notification_processors: 1
        monasca_persister_java_opts: "-Xmx64m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 1
        monasca_persister_metric_batch_size: 500
        storm_nimbus_childopts: "-Xmx32m"
        storm_supervisor_childopts: "-Xmx32m"
        storm_ui_childopts: "-Xmx32m"
        storm_worker_childopts_heap: "-Xmx64m"
        storm_worker_ports: [6701]
        thresh_metric_spouts: 2
        thresh_metric_threads: 2
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 100M
            - name: tm
              maxmemorysize: 100M
    small:
        kafka_heap_opts: "-Xmx256m"
        monasca_api_java_opts: "-Xmx256m"
        monasca_notification_alarm_processors: 1
        monasca_notification_notification_processors: 1
        monasca_persister_java_opts: "-Xmx128m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 200
        monasca_persister_metric_threads: 1
        monasca_persister_metric_batch_size: 500
        storm_nimbus_childopts: "-Xmx64m"
        storm_supervisor_childopts: "-Xmx64m"
        storm_ui_childopts: "-Xmx64m"
        storm_worker_childopts_heap: "-Xmx128m"
        storm_worker_ports: [6701]
        thresh_metric_spouts: 2
        thresh_metric_threads: 2
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 200M
            - name: tm
              maxmemorysize: 200M
    medium:
        kafka_heap_opts: "-Xmx512m -Xms512m"
        monasca_api_java_opts: "-Xmx512m"
        monasca_notification_alarm_processors: 2
        monasca_notification_notification_processors: 2
        monasca_persister_java_opts: "-Xmx512m"
        monasca_persister_alarm_threads: 1
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 2
        monasca_persister_metric_batch_size: 5000
        storm_nimbus_childopts: "-Xmx256m"
        storm_supervisor_childopts: "-Xmx256m"
        storm_ui_childopts: "-Xmx256m"
        storm_worker_childopts_heap: "-Xmx512m"
        storm_worker_ports: [6701, 6702]
        thresh_metric_spouts: 4
        thresh_metric_threads: 4
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 1G
            - name: tm
              maxmemorysize: 1G
    large:
        kafka_heap_opts: "-Xmx1G -Xms1G"
        monasca_api_java_opts: "-Xmx1G"
        monasca_notification_alarm_processors: 2
        monasca_notification_notification_processors: 2
        monasca_persister_java_opts: "-Xmx1G"
        monasca_persister_alarm_threads: 2
        monasca_persister_alarm_batch_size: 100
        monasca_persister_metric_threads: 2
        monasca_persister_metric_batch_size: 10000
        thresh_metric_spouts: 8
        thresh_metric_threads: 8
        vertica_resource_pools_limits:
            - name: wosdata
              maxmemorysize: 2G
            - name: tm
              maxmemorysize: 2G
        storm_nimbus_childopts: "-Xmx512m"
        storm_supervisor_childopts: "-Xmx512m"
        storm_ui_childopts: "-Xmx512m"
        storm_worker_childopts_heap: "-Xmx1280m"
        storm_worker_ports: [6701, 6702, 6703, 6704]

monasca_tunings: "{{ monasca_possible_tunings[tuning_selector] }}"

kafka_log_retention_bytes: 10485760  # 10 MB
storm_version: 0.9.5
storm_nimbus_extra_config:
    nimbus.childopts: "{{ monasca_tunings.storm_nimbus_childopts }}"
storm_supervisor_extra_config:
    supervisor.childopts: "{{ monasca_tunings.storm_supervisor_childopts }}"
storm_ui_extra_config:
    ui.childopts: "{{ monasca_tunings.storm_ui_childopts }}"
storm_worker_extra_config:
    worker.childopts: "{{ monasca_tunings.storm_worker_childopts_heap }} -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote"
storm_worker_ports: "{{ monasca_tunings.storm_worker_ports }}"
influxdb_use_apt: True
# Must be either vertica or influxdb
database_type: vertica
monasca_jars_virtualenv_dir: /opt/stack/service/monasca/venv
monasca_notification_virtualenv_dir: /opt/stack/service/monasca-notification/venv
monasca_api_version: 1.1.0-SNAPSHOT
monasca_persister_version: 1.1.0-SNAPSHOT
monasca_thresh_version: 1.1.0-SNAPSHOT

# Agent Defaults
monasca_agent_virtualenv_dir: /opt/stack/service/monasca-agent/venv
monasca_agent_check_frequency: 30
monasca_agent_system_only: true

# Kafka Defaults
kafka_heap_opts: "{{ monasca_tunings.kafka_heap_opts }}"

# API Defaults
monasca_api_java_opts: "{{ monasca_tunings.monasca_api_java_opts }}"

# Persister Defaults
monasca_persister_java_opts: "{{ monasca_tunings.monasca_persister_java_opts }}"
monasca_persister_alarm_threads: "{{ monasca_tunings.monasca_persister_alarm_threads }}"
monasca_persister_alarm_batch_size: "{{ monasca_tunings.monasca_persister_alarm_batch_size }}"
monasca_persister_metric_threads: "{{ monasca_tunings.monasca_persister_metric_threads }}"
monasca_persister_metric_batch_size: "{{ monasca_tunings.monasca_persister_metric_batch_size }}"

vertica_users:
  - username: "{{ FND_VDB.vars.monitor_user_name }}"
    password: "{{ FND_VDB.vars.monitor_user_password }}"
    role: monitor
  - username: "{{ MON_API.consumes_FND_VDB.vars.vertica_monasca_api_user }}"
    password: "{{ MON_API.consumes_FND_VDB.vars.vertica_monasca_api_password }}"
    role: monasca_api
  - username: "{{ MON_PST.consumes_FND_VDB.vars.vertica_monasca_persister_user }}"
    password: "{{ MON_PST.consumes_FND_VDB.vars.vertica_monasca_persister_password }}"
    role: monasca_persister
vertica_api_user: "{{ MON_API.consumes_FND_VDB.vars.vertica_monasca_api_user }}"
vertica_api_password: "{{ MON_API.consumes_FND_VDB.vars.vertica_monasca_api_password }}"
vertica_persister_user: "{{ MON_PST.consumes_FND_VDB.vars.vertica_monasca_persister_user }}"
vertica_persister_password: "{{ MON_PST.consumes_FND_VDB.vars.vertica_monasca_persister_password }}"
vertica_resource_pools_limits: "{{ monasca_tunings.vertica_resource_pools_limits }}"
vertica_version: 7.1.1-0
vertica_jdbc_jar: "vertica-jdbc-{{ vertica_version }}.jar"
vertica_jdbc_location: "{{ monasca_jars_virtualenv_dir }}/lib/{{ vertica_jdbc_jar }}"
vertica_ssh_key_location: /root
vertica_use_apt: True

# Threshold Engine defaults
thresh_metric_spout_tasks: "{{ monasca_tunings.thresh_metric_spouts }}"
thresh_metric_spout_threads: "{{ monasca_tunings.thresh_metric_threads }}"

# Notification defaults
monasca_notification_alarm_processors: "{{ monasca_tunings.monasca_notification_alarm_processors }}"
monasca_notification_notification_processors: "{{ monasca_tunings.monasca_notification_notification_processors }}"
