#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Install Ceilometer API

- include: ../../_CEI-CMN/tasks/install.yml

- name: Ceilometer API | install | Remove Ceilometer API DPKG (if exists)
  apt: name=ceilometer-api install_recommends=no state=absent force=yes
  ignore_errors: True

- name: CEI-API | install | Update venv Cache
  install_package:
     cache: update

- name: CEI-API | install | Installing Ceilometer API code
  install_package:
     name: ceilometer
     service: ceilometer-api
     state: present
     activate: act_off
  register: ceilometer_api_install_result
  notify: ceilometer_api_change

- name: Ceilometer API | install | Set service conf directories
  set_fact:
    ceilometer_api_conf_dir: "{{ 'ceilometer-api' | config_dir(ceilometer_api_install_result.version) }}"
    ceilometer_api_venv_share_dir: "{{ 'ceilometer-api' | share_dir(ceilometer_api_install_result.version) }}/ceilometer"
    ceilometer_api_bin_dir: "{{ 'ceilometer-api' | bin_dir(ceilometer_api_install_result.version) }}"
    ceilometer_api_activate_required: true

#NOTE: Since Ceilometer runs as Modwsgi we can not set ceilometer api config directory to
#      versioned config directory . It will be default to global_conf i.e. /etc/ceilometer

- name: CEI-API | install | Install modwsgi dependencies
  apt: state=latest name={{ item }}
  sudo: yes
  with_items:
    - libapache2-mod-wsgi
    - libssl-dev
    - libapache2-mod-shib2
    - libffi-dev
    - libmysqlclient18
    - python-httplib2 # Required for ansible url plugin
