# (c) Copyright 2015 Hewlett Packard Enterprise Development Company
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Unpack an arbitrary venv into /opt/stack/venv.
#
# Parameters:
#   source: path to the venv tarball
---

- name: venv-editor | unpack-venv | Ensure package installation directory is removed
  file:
    path: "{{ venv_editor_source_dir }}"
    state: absent
  become: yes
  when: venv_editor_source_dir_stat is defined and not venv_editor_source_dir_stat.stat.exists

- name: venv-editor | unpack-venv | Ensure target directory is removed
  file:
    path: "{{ venv_editor_target_dir }}"
    state: absent
  become: yes
