#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: heat-common | _set_directories | set service etc and venv directory - configure
  set_fact:
    heat_service_conf_dir: "{{ heat_component | config_dir(install_package_result.version) }}/heat"
    heat_service_bin_dir: "{{ heat_component | bin_dir(install_package_result.version) }}"
    heat_service_venv_share_dir: "{{ heat_component | share_dir(install_package_result.version) }}"
  when: install_package_result.version is defined

- name: heat-common | _set_directories | set service etc and venv directory - reconfigure
  set_fact:
    heat_service_conf_dir: "{{ heat_component | config_dir() }}/heat"
    heat_service_bin_dir: "{{ heat_component | bin_dir() }}"
    heat_service_venv_share_dir: "{{ heat_component | share_dir() }}"
  when: install_package_result.version is undefined

- name: heat-common | _set_directories | set plugins directory
  set_fact:
    heat_plugins_dir: "{{ heat_service_venv_share_dir }}/lib/heat"
    heat_docker_plugin_source_dir: "{{heat_service_venv_share_dir}}/heat/contrib/heat_docker/heat_docker"
