#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Setting up the neutron-vpn-agent specific config files
---
- include: _write_conf.yml
  src: "../templates/vpn_agent.ini.j2"
  dest: "vpn_agent.ini"

- name: Neutron Common | configure_vpn_agent | vpn_agent.ini change
  set_fact:
    neutron_vpn_agent_restart_required: true
  when: write_conf_result.changed==true
  
- include: _write_conf.yml
  src: "../templates/vpn-agent-logging.conf.j2"
  dest: "vpn-agent-logging.conf"

- name: Neutron Common | configure_vpn_agent | vpn-agent-logging.conf change
  set_fact:
    neutron_vpn_agent_restart_required: true
  when: write_conf_result.changed==true
