#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: SWF-EXP | configure | Enable the swift expirer services to start on boot
  command: systemctl enable "{{ item.key }}"
  with_dict: swift_expirer_services

- name: SWF-EXP | configure | Copy object-expirer.conf
  template:
    src: object-expirer.conf.j2
    dest: "{{ swift_expirer_conf_dir }}/object-expirer.conf"
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0400
  notify:
    - swift_expirer_config_change
