#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: SWF-EXP | start | Activate the latest install
  install_package:
    name: swift
    service: "{{ item.item.key }}"
    activate: act_on
    version: "{{ item.version }}"
  with_items: swift_expirer_install_result.results
  when: swift_expirer_install_result is defined

# For now restart rather than reload
# Skip if a restart is required
# No need to restart here if swift-expirer restart is also happening
- name: SWF-EXP | start | Reload the Swift Expirer services
  service:
    name: "{{ item.key }}"
    state: restarted
  with_dict: swift_expirer_services
  when: swift_expirer_reload_required and (not swift_restart_required) and
        (not swift_expirer_restart_required)

- name: SWF-EXP | start | Restart the Swift Expirer services
  service:
    name: "{{ item.key }}"
    state: restarted
  with_dict: swift_expirer_services
  when: swift_restart_required or swift_expirer_restart_required

- name: SWF-EXP | start | Start the Swift Expirer services
  service:
    name: "{{ item.key }}"
    state: started
  with_dict: swift_expirer_services
