#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Ironic Pre Configure | keystone_conf | Get a domain scoped token
  keystone_v3:
    endpoint: "{{ keystone.endpoint }}"
    login_username: "{{ keystone.admin_user }}"
    login_password: "{{ keystone.admin_password }}"
    login_user_domain_name: "{{ keystone.default_domain }}"
    login_domain_name: "{{ keystone.default_domain }}"
    action: "token_get"
  run_once: true
  register: domain_scoped_token

- name: Ironic Pre Configure | keystone_conf | create ironic service user
  keystone_v3:
    action : "create_user"
    endpoint: "{{ keystone.endpoint }}"
    login_token: "{{ domain_scoped_token.result }}"
    user_name: "{{ keystone.ironic_admin_user }}"
    user_password: "{{ keystone.ironic_admin_password }}"
    user_domain_name: "{{ keystone.default_domain }}"
  run_once: true

- name: Ironic Pre Configure | keystone_conf | create ironic service user-role assignment
  keystone_v3:
    action: "grant_project_role"
    endpoint: "{{ keystone.endpoint }}"
    login_token: "{{ domain_scoped_token.result }}"
    project_name: "{{ keystone.service_tenant }}"
    user_name: "{{ keystone.ironic_admin_user }}"
    role_name: "{{ keystone.role }}"
    user_domain_name: "{{ keystone.default_domain }}"
    project_domain_name: "{{ keystone.default_domain }}"
  run_once: true

- name: Ironic Pre Configure | keystone_conf | create ironic service
  keystone_v3:
    action: "create_service"
    endpoint: "{{ keystone.endpoint }}"
    login_token: "{{ domain_scoped_token.result }}"
    service_type: "baremetal"
    service_name: "ironic"
    description: "OpenStack Baremetal Service"
  run_once: true

- name: Ironic Pre Configure | keystone_conf | create ironic service endpoint
  keystone_v3:
    action: "create_endpoint"
    endpoint: "{{ keystone.endpoint }}"
    login_token: "{{ domain_scoped_token.result }}"
    service_name: "ironic"
    region: "{{ endpoints.region }}"
    admin_url: "{{ endpoints.adminurl }}"
    internal_url: "{{ endpoints.internalurl }}"
    public_url:
  run_once: true
