#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: swiftlm-ring-supervisor | configure | Create swift ring supervisor dirs
  file:
    path: "{{ swiftlm_etc }}/{{ item }}"
    state: directory
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0755
  with_items:
  - builder_dir
  - deploy_dir

- name: swiftlm-ring-supervisor | configure | Create hosts file
  copy:
    src: "../../../net/hosts.hf"
    dest: "{{ swiftlm_etc }}/hosts.hf"
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0400

- name: swiftlm-ring-supervisor | configure | Create input model file
  template:
    src: input-model.j2
    dest: "{{ swiftlm_etc }}/input-model.yml"
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0400

- name: swiftlm-ring-supervisor | configure | Create consumes file
  template:
    src: swift_ring_builder_consumes.j2
    dest: "{{ swiftlm_etc }}/swift_ring_builder_consumes.yml"
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0400

- name: swiftlm-ring-supervisor | configure | Create drive_configurations dirs
  file:
    path: "{{ swiftlm_etc }}/drive_configurations/{{ item }}"
    state: directory
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0755
  with_items: "{{ swift_storage_servers }}"

- name: swiftlm-ring-supervisor | configure | Create drive configurations file
  template:
    src: drive_configuration.j2
    dest: "{{ swiftlm_etc }}/drive_configurations/{{ item }}/drive_configuration.yml"
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    mode: 0400
  with_items: "{{ swift_storage_servers }}"