#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: FND-AP2 | install | Install apache2
  become: yes
  apt:
    name: apache2
    install_recommends: no
    state: present
    force: yes
  register: _install_apache_result

- name: FND-AP2 | install | Stop apache only after initialization
  include: stop.yml
  when: _install_apache_result.changed

- name: FND-AP2 | install | Fix up unit file
  include: ../../systemd-sysv-fixup/tasks/fix-unit.yml
  vars:
    units:
      - apache2
