#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Include list of common kernel modules
  include_vars: helion_kernel_modules.yml

- name: Load required kernel modules
  modprobe: name={{ item }} state=present
  with_items: kernel_modules | default([])

- name: Persist kernel modules for reboot
  template:
    src: sysctl_modules_load.conf.j2
    dest: "{{ sysctl_kernel_module_file }}"
    owner: root
    group: root
    mode: '0640'

- name: Configure kernel parameters
  template:
    src: helion_sysctl.conf.j2
    dest: "{{ helion_sysctl_conf_file }}"
    owner: root
    group: root
    mode: '0640'
  notify:
    - Load sysctl settings from file

