#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Glance's Keystone configuration
---

- name: glance-post-configure | configure | Get a domain scoped token
  keystone_v3: >
    endpoint={{ keystone_admin_endpoint }}
    login_username={{ keystone_admin_user }}
    login_password={{ keystone_admin_password }}
    login_user_domain_name={{ keystone_user_domain_name }}
    login_domain_name={{ keystone_user_domain_name }}
    action="token_get"
  register: domain_scoped_token

# The service user is used for Keystone middleware auth.
- name: glance-post-configure | configure | Create Glance service user in Keystone
  keystone_v3: >
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="create_user"
    user_name={{ glance_admin_user }}
    user_domain_name={{ keystone_user_domain_name }}
    user_password={{ glance_admin_password }}
  run_once: True

- name: glance-post-configure | configure | Add admin role to Glance service user in Keystone
  keystone_v3:
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="grant_project_role"
    user_name={{ glance_admin_user }}
    project_name={{ KEY_API.vars.keystone_service_tenant }}
    user_domain_name={{ keystone_user_domain_name }}
    project_domain_name={{ keystone_project_domain_name }}
    role_name={{ KEY_API.vars.keystone_admin_role }}
  run_once: True

- name: glance-post-configure | configure | Create Keystone project for storing image data in Swift backend
  keystone_v3: >
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="create_project"
    project_name={{ glance_swift_tenant_name }}
    description="Tenant for storing Glance image data in Swift"
    project_domain_name={{ keystone_project_domain_name }}
  run_once: true

- name: glance-post-configure | configure | Create Keystone user for storing image data in Swift backend
  keystone_v3: >
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="create_user"
    user_name={{ glance_swift_user }}
    user_domain_name={{ keystone_user_domain_name }}
    user_password={{ glance_swift_password }}
    role_name={{ KEY_API.vars.keystone_member_role }}
  run_once: True

- name: glance-post-configure | configure | Add role to Glance data user in Keystone
  keystone_v3:
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="grant_project_role"
    user_name={{ glance_swift_user }}
    project_name={{ glance_swift_tenant_name }}
    user_domain_name={{ keystone_user_domain_name }}
    project_domain_name={{ keystone_project_domain_name }}
    role_name={{ KEY_API.vars.keystone_member_role }}
  run_once: True

- name: glance-post-configure | configure | Create Glance service in Keystone
  keystone_v3: >
    endpoint={{ keystone_admin_endpoint }}
    login_token={{ domain_scoped_token.result }}
    action="create_service"
    service_type={{ GLA_API.advertises.keystone_service_type }}
    service_name={{ GLA_API.advertises.keystone_service_name }}
    description='Image Service'
  run_once: True

- name: glance-post-configure | configure | Create Glance endpoint in Keystone
  keystone_v3: >
    endpoint={{ keystone_admin_endpoint }}
    login_token={{ domain_scoped_token.result }}
    action="create_endpoint"
    service_name={{ GLA_API.advertises.keystone_service_name }}
    region={{ GLA_API.advertises.vips.public[0].region_name }}
    admin_url="{{ GLA_API.advertises.vips.private[0].url }}"
    internal_url="{{ GLA_API.advertises.vips.private[0].url }}"
    public_url="{{ GLA_API.advertises.vips.public[0].url }}"
  run_once: True
