#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Glance's upgrade specific Keystone configuration
---

- name: glance-upgrade-configure | configure | Get a domain scoped token
  keystone_v3: >
    endpoint={{ keystone_admin_endpoint }}
    login_username={{ keystone_admin_user }}
    login_password={{ keystone_admin_password }}
    login_user_domain_name={{ keystone_user_domain_name }}
    login_domain_name={{ keystone_user_domain_name }}
    action="token_get"
  register: domain_scoped_token

# Handle the case where a new Swift password has been specified during upgrade
- name: glance-upgrade-configure | configure | Set Glance data user credentials
  keystone_v3: >
    login_token={{ domain_scoped_token.result }}
    endpoint={{ keystone_admin_endpoint }}
    action="reset_password_by_admin"
    user_name={{ glance_swift_user }}
    user_domain_name={{ keystone_user_domain_name }}
    user_password={{ glance_swift_password }}
