#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

freezer_ssh_host:
freezer_ssh_port:
freezer_ssh_username:
freezer_ssh_base_dir:
freezer_ssh_private_key:


# To write the ssh key on multiple lines, use this syntax:
# Please, note the pipe on the first line and the two space indent on the following lines

#freezer_ssh_private_key: |
#  -----BEGIN RSA PRIVATE KEY-----
#  MIIEpAIBAAKCAQEAuOWtzWsy8/STJzKd18pQJC/XNj1YXTimawjc0l/uFsT+BDvr
#  U05edrIbI4tSkVFfMdVYHP6BSAHHfOL2ZfQItNtoZZZ4t8qfNcKtXJShHouWfs9K
#  6elGAecTOOlXhHVCnwPglKyf3Qq8/Lspm+jMP49W/J8ipZdYjld72vtPBGyhAqNa
#  Q0rYT4d2uOBkNrzQ/AHYGwAIozmrMx3jJV4E7daaEw9O/ax1hjDB+WTVV9fgJINP
#  Qs1VdqQhuNgYVIkshJLZ+d5HLokXcyxTcDT9wDrJ7a5Xskn0I1/NIM60UvbhwpzM
#  SuLCr6m2zYvcWj+zlUhoqcFC7sHRnnOtpl88TQIDAQABAoIBAQCmJaXfYEQCGjWd
#  VIuoHGGVkvPWBpv/8OcCaY1c8d0V0uDb1ygozNRv3q4qa4i/kppzQl4Sd9SeaxLi
#  s2RsyzSDqGGQX/2MUmRsv8pe1iROOWr7+rQ7q2ZAUW/hhTUijuhV0fsePlzNGVgn
#  1tuWAUSAnQKysSFGIdDu38gpSAiCVL8QV1ch5F46VfsJQYI2trHBAM3FxKceAbGE
#  vN2j4xV5q5G0TlA4jZttb/6aqyvysopFnlTssN+42N8Es7KRQnIg6X1piHptyBQo
#  /mZkxewZVRi5SEzE70z9gg5+E7+h53j+0EBzJSai/VFb+SqIo42Ep8Ayb2SsD65s
#  RrlUTqQVAoGBAOkKpxBJzHqj2U28Y9dg4ykIoEzmJ0szTwcD2TFKy2yADyAIbLU1
#  LxLEuTXKL9YPnxaeDugN6lgUj/nLOd2rPmUnQk7R3btDGu+8fW6QC0SSK7lPlD82
#  baQ8L8RTzr5A9VL6zqKNl9EygCGeBMZtyVidudjKF4Y4Q3JzQQf4sMTnAoGBAMsc
#  0OUfcxbXd4VXhywVOKznPMX63CckAWeFKwLM9YBfnuv7TrkI0DSFTFIZ33MawjWh
#  YtxPigJKx89YutBeSMlA//UMprT9NjNb45Y8xlVzGgPJs89nuHeLWRre6JNWjtuc
#  2xKRb/1RCCBqNuThqxaZwpwEuADrfat2n0s3idqrAoGBAOFxVL0FJ7Nc3tO89Dlf
#  mWIQ3kKGRG0TbdgzeOGeobyNBhTPEZsboDZf6WyH9E75PcX7kiAbliEvgzj7yTcQ
#  eoQQvqzRidemy2Aw0IctAjmLzpCu05NzbA39y5f6G38iCDIGP/AxWjUezaW34Ja1
#  jpsTur5mguttcpI9vSOhCiDxAoGAJpQymVJ/6bbDXPBjHFxrh2vkfzZG2qhcG+2P
#  XdjQSLHg3bG+IicqZM9sz6taZeKPQOCGhpIVBJpvmVKhKTK/YHqYI1Nj1rzBrr+l
#  WsPwaAqUxmNpY9uvjgVJx3DPfCzUtaH1enFldBgQExgZlR/H/2L1M+0xhfs0w3yk
#  hQTnikECgYBJTdVd921n5HDd8eooDMd48UwkKK57OdWxTniO5blyyyzQfV6dBY+A
#  NnkiIbTGI88Y/Bx8vWMzFJOgd4O+mXDkyXBfj6Cq/VFPf7RtAoNcNLZ0LwpEb52u
#  LDjUGJ+wf4SxU3fBDuxUaNCdZrJRtx1S59WxsQkaiTwHexw1Pi7G1g==
#  -----END RSA PRIVATE KEY-----
