#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: KEY_API |  _venv_install | Update the venv Cache
  install_package:
    cache: update
  become: yes
  tags:
    - keystone

- name: KEY_API |  _venv_install | Install Keystone
  install_package:
    name: keystone
    service: keystone
    state: present
    activate: act_off
  become: yes
  register: keystone_venv_install_result
  tags:
    - keystone

- name: KEY-API | _venv_install | Set facts about the venv
  set_fact:
     keystone_venv_install_conf_dir: "{{ 'keystone' | config_dir(keystone_venv_install_result.version) }}"
     keystone_venv_install_share_dir: "{{ 'keystone' | share_dir(keystone_venv_install_result.version) }}/"
     keystone_bin_dir: "{{ 'keystone' | bin_dir(keystone_venv_install_result.version) }}/"

- name: KEY_API | _venv_install | Debug venv varable
  debug:  var=keystone_venv_install_result
  tags:
    - keystone
    - keystone_debug
  when: keystone_debug is defined
  run_once: True

- name: KEY_API | _venv_install | Activate the Venv
  install_package:
    name: keystone
    service: keystone
    activate: act_on
    version: "{{ keystone_venv_install_result.version }}"
  when: keystone_venv_install_result is defined
  notify: keystone_change
  tags:
    - keystone

- name: KEY-API | _venv_install  | Touch the log file
  file:
    path: "{{ item }}"
    owner: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    mode: 0644
    state: touch
  become: yes
  become_user: "{{ keystone_user }}"
  with_items:
    - "/var/log/keystone/keystone.log"
    - "/var/log/keystone/keystone-json.log"
  tags:
    - keystone


- name: KEY-API | _venv_install  | Copies file to venv conf dir
  template:
    src: "{{ item.src }}"
    dest: "{{ keystone_venv_install_conf_dir }}/{{ item.dest }}"
    owner: "{{ keystone_user }}"
    group: "{{ keystone_group }}"
    mode: 0600
  with_items:
   - { src: policy.v3cloudsample.json , dest: policy.json }
   - { src: keystone.conf.j2 , dest: keystone.conf }
   - { src: logging.conf.j2 , dest: logging.conf }
  become: yes
  notify: keystone_change
  tags:
    - keystone


- name: KEY-API | _venv_install | Create symbolic link for startup file
  file:
    src: "{{ keystone_venv_install_share_dir }}/keystone/httpd/keystone.py"
    dest: "/var/www/keystone/{{ item }}"
    owner: root
    group: "{{ keystone_group }}"
    state: link
  with_items:
    - main
    - admin
  tags:
    - keystone

# Temporary patch to enable upgrade from Beta1 to Beta 2 without manual workaround
- name: KEY-API | _venv_install | Remove the files that are in Beta 1
  file:
    path={{ keystone_conf_dir }}/{{ item }}
    state=absent
  with_items:
    - keystone.conf
    - logging.conf
    - policy.json
    - keystone-paste.ini
  become: yes
  ignore_errors: True
  tags:
    - keystone

- name: KEY-API | _venv_install | Create Symlink for Keystone paste ini from venv
  file:
    src="{{ keystone_venv_install_share_dir }}/keystone/etc/{{ item }}"
    dest={{ keystone_conf_dir }}/{{ item }}
    owner={{ keystone_user }}
    group={{ keystone_group }}
    state=link
  with_items:
    - keystone-paste.ini
  tags:
    - keystone

- name: KEY-API | _venv_install | Create Symlinks for  other config files from install
  file:
    src="{{ keystone_venv_install_conf_dir }}/{{ item }}"
    dest={{ keystone_conf_dir }}/{{ item }}
    owner={{ keystone_user }}
    group={{ keystone_group }}
    state=link
  with_items:
    - keystone.conf
    - logging.conf
    - policy.json
  tags:
    - keystone
