#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

freezer_keystone_identity_uri: "{{ FRE_API.consumes_KEY_API.vips.admin[0].url }}"
freezer_keystone_auth_uri: "{{ FRE_API.consumes_KEY_API.vips.private[0].url }}"
freezer_keystone_service_user: "{{ FRE_API.consumes_KEY_API.vars.keystone_freezer_user }}"
freezer_keystone_service_password: "{{ FRE_API.consumes_KEY_API.vars.keystone_freezer_password | quote }}"
freezer_keystone_service_tenant_name: "{{ KEY_API.vars.keystone_service_tenant }}"

freezer_bind_host: "{{ host.bind.FRE_API.admin.ip_address }}"
freezer_bind_port: "{{ host.bind.FRE_API.admin.port }}"
freezer_vip_url: "{{ FRE_API.advertises.vips.private[0].url }}"

freezer_system_user: freezer
freezer_system_group: freezer

freezer_api_venv_conf_dir: "{{ 'freezer-api' | config_dir() }}"
freezer_api_venv_bin_dir: "{{ 'freezer-api' | bin_dir() }}"
freezer_api_log_dir: "/var/log/freezer-api"
freezer_api_log_python: "{{ freezer_api_log_dir }}/freezer-api.log"
freezer_api_log_access: "{{ freezer_api_log_dir }}/freezer-api-access.log"
freezer_api_log_wsgi: "{{ freezer_api_log_dir }}/freezer-api-modwsgi.log"

# Tuning
freezer_api_token_cache_time: 3600
freezer_api_process_count: 4
freezer_api_thread_count: 4
freezer_api_socket_timeout: 300
freezer_api_http_request_max_retries: 5
freezer_api_elasticsearch_retries: 20
freezer_api_elasticsearch_timeout: 60

freezer_api_restart_required: false
freezer_api_conf_symlinks:
  - { dst: '/etc/freezer-api.conf', src: 'freezer-api.conf' }
