#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
hlmuser_home: "{{ ansible_env['HOME'] }}"

location: helion

valid_dirs:
  helion:
    - "{{ hlmuser_home }}/helion/hos/ansible"
  deploy:
    - "{{ git_operations.ansible_target_dir }}/next/hos/ansible"
    - "{{ git_operations.ansible_target_dir }}/last/hos/ansible"

warning:
  helion: >
    The current playbook is designed to be run from
    ~/helion/hos/ansible. If you run it from an alternative
    directory, the results could be unpredictable.
  deploy: >
    Deployments should be run from the ansible directory
    under {{ git_operations.ansible_target_dir }}/next.
    The configuration processor output is not available to
    Ansible playbooks run from another location.

    In order to run a deployment, run the configuration
    processor first using
    "ansible-playbook -i hosts/localhost config-processor-run.yml";
    then ready the deployment directory structure using
    "ansible-playbook -i hosts/localhost ready-deployment.yml".
