#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Configure the nova-scheduler service
---
- include: ../../nova-common/tasks/_set_directories.yml
  vars:
    install_package_result: "{{ nova_scheduler_install_result }}"
- include: ../../nova-common/tasks/configure.yml

- name: NOV-SCH | configure | notify on rootwrap change
  set_fact:
    nova_scheduler_restart_required: true
  when: rootwrap_changed

- include: ../../nova-common/tasks/_write_conf.yml
  src: "../../NOV-SCH/templates/scheduler.conf.j2"
  dest: "{{ nova_service_conf_dir}}/scheduler.conf"
  owner: "{{ nova_system_user }}"
  group: "{{ nova_system_group }}"

# We need to be sure that the hypervisor.conf file is present
- name: NOV-SCH | configure | touch hypervisor.conf
  become: yes
  file:
    path: "{{ nova_service_conf_dir }}/hypervisor.conf"
    state: touch
    owner: "{{ nova_system_user }}"
    group: "{{ nova_system_group }}"

- name: NOV-SCH | configure | notify on scheduler.conf change
  set_fact:
    nova_scheduler_restart_required: true
  when: write_conf_result.changed

- name: NOV-SCH | configure | Apply template
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ nova_service_conf_dir }}/{{ item }}"
    owner: root
    group: "{{ nova_system_group }}"
    mode: 0640
  with_items:
    - scheduler-logging.conf
  notify:
    - nova_scheduler_config_change
