#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: OpenStack Alarm definitions
  monasca_alarm_definition:
    name: "{{item.name}}"
    description: "{{item.description | default('') }}"
    expression: "{{item.expression}}"
    keystone_token: "{{default_notification.keystone_token}}"
    match_by: "{{item.match_by | default(['hostname']) }}"
    monasca_api_url: "{{default_notification.monasca_api_url}}"
    severity: "{{item.severity | default('LOW') }}"
    alarm_actions:
      - "{{default_notification.notification_method_id}}"
    ok_actions:
      - "{{default_notification.notification_method_id}}"
    undetermined_actions:
      - "{{default_notification.notification_method_id}}"
  run_once: True
  with_items:
    - { name: "Instance CPU Usage", description: "Alarms when the CPU usage of the specified instance is high", expression: "avg(cpu.utilization_perc) > 90 times 3", match_by: [resource_id] }
