#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: SWF-PRX | start | Activate the latest install
  install_package:
    name: swift
    service: "{{ item.item.key }}"
    activate: act_on
    version: "{{ item.version }}"
  with_items: swift_proxy_install_result.results
  when: swift_proxy_install_result is defined

- name: SWF-PRX | start | Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  when: swift_common_rsyslog_restart_required

- set_fact:
    swift_common_rsyslog_restart_required: false
  when: swift_common_rsyslog_restart_required

# For now restart rather than reload
# No need to restart here if swift-proxy restart is also happening
- name: SWF-PRX | start | Reload the Swift Proxy services
  service:
    name: swift-proxy-server
    state: restarted
  with_dict: swift_proxy_services
  when: swift_proxy_reload_required and (not swift_restart_required) and
        (not swift_proxy_restart_required)

- name: SWF-PRX | start | Restart the Swift Proxy services
  service:
    name: "{{ item.key }}"
    state: restarted
  with_dict: swift_proxy_services
  when: swift_restart_required or swift_proxy_restart_required

- name: SWF-PRX | start | Start the Swift Proxy services
  service:
    name: "{{ item.key }}"
    state: started
  with_dict: swift_proxy_services
